- autoload/indent_blankline.vim
- autoload/indent_blankline/callback.vim
- doc/indent_blankline.txt
- plugin/indent_blankline.vim
* Error logs have more context
* More error logs
* Added `g:indent_blankline_debug` option to only display the errors logs
when needed
> Version 1.3.0

- autoload/indent_blankline.vim
- doc/indent_blankline.txt
* Moved more of init function in the try/catch
> Version 1.3.1

- autoload/indent_blankline/embedded.vim
- doc/indent_blankline.txt
* Call indentexpr with `silent!` to not exit early on errors
> Version 1.3.2

- README.md
- doc/indent_blankline.txt
* Fix windows working directory bug
> Version 1.4.1

- lua/indent_blankline/init.lua
- lua/indent_blankline/utils.lua
fixed find_indent() according to #120
> Fixed irregular indentation

- README.md
- doc/indent_blankline.txt
- lua/indent_blankline/init.lua
- lua/indent_blankline/utils.lua
- plugin/indent_blankline.vim
* Add setup function
* Support buffer, tab and global variables
resolves #96, resolves #145
> Add setup function

- lua/indent_blankline/init.lua
Use `leftcol` offset to calculate virtual text when scrolled horizontally.
fix #51
> Fix horizontal scroll

- README.md
- doc/indent_blankline.txt
- lua/indent_blankline/init.lua
- lua/indent_blankline/utils.lua
- plugin/indent_blankline.vim
* Added setup function
* Added buffer variables
* Fix horizontal scroll
> Version 2.1.0

- lua/indent_blankline/init.lua
- plugin/indent_blankline.vim
> bug: always run setup function

- doc/indent_blankline.txt
* Fix bug were setup function is not run
> Version 2.1.1

- lua/indent_blankline/init.lua
- plugin/indent_blankline.vim
Move the setup and init functions around a bit to handle lazy loading
fix #160
> bug: fix lazy loading

- doc/indent_blankline.txt
- lua/indent_blankline/init.lua
- plugin/indent_blankline.vim
> Version 2.1.2

- doc/indent_blankline.txt
- plugin/indent_blankline.vim
> Version 2.1.3

- doc/indent_blankline.txt
- lua/indent_blankline/init.lua
- lua/indent_blankline/utils.lua
* Fix race condition in `is_indent_blankline_enabled`
> Version: 2.1.4

- README.md
> Add pr check github workflow

- doc/indent_blankline.txt
- lua/indent_blankline/init.lua
- lua/indent_blankline/utils.lua
- plugin/indent_blankline.vim
* Add `indent_blankline_respect_list` option
> Version 2.3.0

- doc/indent_blankline.txt
- lua/indent_blankline/init.lua
- lua/indent_blankline/utils.lua
* Remove `indent_blankline_respect_list`
* Add `indent_blankline_disable_with_nolist`
> Version 2.4.0

- doc/indent_blankline.txt
- lua/indent_blankline/init.lua
* Add `indent_blankline_max_indent_increase`
> Version 2.5.0

- .github/workflows/pr_check.yml
- doc/indent_blankline.txt
- lua/indent_blankline/init.lua
- lua/indent_blankline/utils.lua
- stylua.toml
* Only load treesitter libs if needed
> Version 2.5.1

- README.md
> bug: fix background highlight example

- README.md
- doc/indent_blankline.txt
* Fix background highlight example
> Version 2.5.2

- README.md
- lua/indent_blankline/init.lua
> bug: remove old `space_char` reference

- README.md
- doc/indent_blankline.txt
- lua/indent_blankline/init.lua
* Remove old reference to `indent_blankline_space_char`
> Version: 2.5.3

- doc/indent_blankline.txt
- lua/indent_blankline/init.lua
* Fix wrong indent for empty lines with only extra
> Version: 2.5.4

- README.md
- doc/indent_blankline.txt
- lua/indent_blankline/init.lua
- lua/indent_blankline/utils.lua
* Fix typo in readme
* Fix initialization of `g:indent_blankline_space_char_blankline_highlight_list`
* Refactor `find_indent`
> Version: 2.5.5

- lua/indent_blankline/init.lua
> bug: fix trailing space for blanklines

- doc/indent_blankline.txt
- lua/indent_blankline/init.lua
* Fix trailing space for blanklines
> Version: 2.5.6

- README.md
- lua/indent_blankline/init.lua
* update the README to not overwrite all listchars
* handle listchars without a tab character
fix #241
> bug: fix no tab character in listchars

- README.md
- doc/indent_blankline.txt
- lua/indent_blankline/init.lua
* update the README to not overwrite all listchars
* handle listchars without a tab character
> Verison 2.5.7

- doc/indent_blankline.txt
- lua/indent_blankline/init.lua
- lua/indent_blankline/utils.lua
* Add `g:indent_blankline_context_pattern_highlight`
> Version 2.6.0

- lua/indent_blankline/init.lua
> Wait until buffer is loaded

- doc/indent_blankline.txt
- lua/indent_blankline/init.lua
* Wait until buffer is loaded before doing anything
> Version 2.6.1

- doc/indent_blankline.txt
- lua/indent_blankline/init.lua
* Fix indent cache for scrolling
* Fix documentation tags
> Version 2.9.3

- README.md
- doc/indent_blankline.txt
- lua/indent_blankline/init.lua
- lua/indent_blankline/utils.lua
* Add `g:indent_blankline_show_current_context_start`
* Add `hl-IndentBlanklineContextStart`
> Version 2.10.0

- doc/indent_blankline.txt
- lua/indent_blankline/init.lua
- lua/indent_blankline/utils.lua
* Remove `nocombine` from `hl-IndentBlanklineContextStart`
> Version 2.10.1

- lua/indent_blankline/init.lua
> bug: move context start extmark after indent

- doc/indent_blankline.txt
- lua/indent_blankline/init.lua
* Apply context start highlight after indentation
> Version 2.10.2

- lua/indent_blankline/init.lua
- lua/indent_blankline/utils.lua
* Fix context start highlight column for files indent with tab
* Fix context start highlight on lines with no indent
fix #310
> bug: fix context start column and without indent

- doc/indent_blankline.txt
- lua/indent_blankline/init.lua
- lua/indent_blankline/utils.lua
* Fix context start highlight column for files indent with tab
* Fix context start highlight on lines with no indent
> Version 2.10.3

- lua/indent_blankline/utils.lua
> bug: remove nocombine from context start highlight

- doc/indent_blankline.txt
- lua/indent_blankline/utils.lua
* Remove `nocombine` from `hl-IndentBlanklineContextStart` again..
> Version 2.10.4

- lua/indent_blankline/commands.lua
> bug: run refresh without autocmds

- doc/indent_blankline.txt
- lua/indent_blankline/commands.lua
* Run refresh without autocmds
* Check that the window is valid before returning to it after refresh
> Version 2.10.5

- README.md
- doc/indent_blankline.txt
* Update example setup in the readme and docs
> Version 2.10.6

- doc/indent_blankline.txt
- lua/indent_blankline/init.lua
> disable current context start on current line

- doc/indent_blankline.txt
- lua/indent_blankline/init.lua
* Add `g:indent_blankline_show_current_context_start_on_current_line`
> Version 2.11.0

- lua/indent_blankline/init.lua
> feature: set ext mark priority

- doc/indent_blankline.txt
- lua/indent_blankline/init.lua
> Version 2.12.1

- doc/indent_blankline.txt
- lua/indent_blankline/init.lua
* Add `g:indent_blankline_char_blankline` and `g:indent_blankline_char_list_blankline` options
> Version 2.14.0

- doc/indent_blankline.txt
- lua/indent_blankline/init.lua
* Add `g:indent_blankline_context_char_blankline` and `g:indent_blankline_context_char_list_blankline` options
> Version 2.15.0

- doc/indent_blankline.txt
- lua/indent_blankline/utils.lua
> Version 2.15.1

- doc/indent_blankline.txt
- lua/indent_blankline/init.lua
- lua/indent_blankline/utils.lua
Add `man` to `g:indent_blankline_filetype_exclude`
Stylua update
> Version 2.16.0

- doc/indent_blankline.txt
- lua/indent_blankline/init.lua
* Update defaults for `g:indent_blankline_buftype_exclude`
> Version 2.17.0

- doc/indent_blankline.txt
- lua/indent_blankline/init.lua
- lua/indent_blankline/utils.lua
Add `g:indent_blankline_use_treesitter_scope`
Update `g:indent_blankline_context_patterns`
> Version 2.18.0

- doc/indent_blankline.txt
- lua/indent_blankline/utils.lua
> Version 2.18.2

- doc/indent_blankline.txt
- lua/indent_blankline/utils.lua
Don't set ext marks when the plugin is already disabled
> Version 2.18.3

- lua/indent_blankline/init.lua
> bugfix: check if buffer is loaded

- doc/indent_blankline.txt
- lua/indent_blankline/init.lua
Check if buffer is loaded before setting ext marks
> Version 2.18.4

- doc/indent_blankline.txt
- lua/indent_blankline/init.lua
> feature: add extmark priority

- doc/indent_blankline.txt
- lua/indent_blankline/init.lua
> Add context_space_char_highlight

- doc/indent_blankline.txt
- lua/indent_blankline/init.lua
- lua/indent_blankline/utils.lua
* Add `hl-IndentBlanklineContextSpaceChar`
* Add `g:indent_blankline_char_priority`
* Add `g:indent_blankline_context_start_priority`
* Use `vim.notify()`
> Version 2.19.0

- doc/indent_blankline.txt
- lua/indent_blankline/utils.lua
> Version 2.19.1

- README.md
- doc/indent_blankline.txt
- lua/indent_blankline/init.lua
- lua/indent_blankline/utils.lua
- plugin/indent_blankline.vim
- Add `OptionSet:listchars` and `CursorMovedI` to refresh trigger
- Add `prompt` to excluded `buftypes`
> Version 2.20.0

- doc/indent_blankline.txt
> fix help tag

- LICENSE.md
- README.md
- doc/indent_blankline.txt
- Remove changelog from doc
- Update readme and doc
> Version 2.20.2

- README.md
- doc/indent_blankline.txt
> docs: Fix typos, reformat code and add lazy.nvim instructions

- lua/indent_blankline/init.lua
- lua/indent_blankline/utils.lua
> Check treesitter language exists

- lua/ibl/autocmds.lua
Fixes #615 
Also fixes a typo with the "FileType" event (it should be uppercase T).
> fix: refresh on TextChangedI

- lua/ibl/init.lua
> fix: remove schedule from init

- lua/ibl/utils.lua
> fix: empty filetype exclude

- lua/ibl/config.lua
- lua/ibl/utils.lua
- specs/features/config_spec.lua
don't allow unsupported keys in the configuration
> feat: config extra key validation

- lua/ibl/config.lua
> fix: scope char config validation

- lua/ibl/utils.lua
- specs/features/utils_spec.lua
> feat: add support for hex in listchars

- lua/ibl/init.lua
> fix: single line buffer

- lua/ibl/init.lua
Not sure if this should be a feature or a bug. I went with bug since it *feels* like the indent shouldn't break for skipped lines at 0 indent.
Not sure how this impacts performance, in a simple ad-hoc test it was slower by 1.88% but I didn't repeat it so that might just be variance. I feel like this should be faster since it moves the `hooks.get` call outside of the main loop, but idk.
> fix: extend indent lines through skipped lines

- lua/ibl/inlay_hints.lua
> fix: lsp methods

- lua/ibl/init.lua
> fix: skip lines hook

- lua/ibl/inlay_hints.lua
> fix(inlay-hints): check if buffer is unloaded

- lua/ibl/init.lua
> fix: scope fill char

- lua/ibl/autocmds.lua
I don't move that much in insert mode usually, but when I do, it is nicer with this addition to the auto commands.
> feat: add `CursorMovedI` autocmd

- lua/ibl/hooks.lua
The current implementation of the hook to extract highlight info from extmarks is _really slow_. Slow to the point where, in neovide, there's a 1-2s lag between me starting to scroll with my mouse and anything happening if `current_scope` is enabled. The changes in this PR make the scrolling happen immediately, and I also no longer get any lags when moving my cursor by holding a down or up key, which is happening (especially with files larger than ~200ish lines) on master.
For the most part, this should be equivalent to the old code; in _theory_, there could be cases where the nested iteration yields a different answer, but I believe that it would require _two_ of the highlights we are looking for to be applied at the same buffer position, and I don't think that that is really an edge …
> perf: make the scope from extmarks hook fast

- lua/ibl/hooks.lua
> fix: scope highlight from extmark hook

- lua/ibl/hooks.lua
> fix: highlight from extmark hook

- lua/ibl/hooks.lua
- lua/ibl/indent.lua
- lua/ibl/utils.lua
> refactor: Use custom vim.split without validate

- lua/ibl/scope_languages.lua
> fix: remove chunk from lua scopes

- lua/ibl/indent.lua
- specs/features/indent_spec.lua
> fix: tab indent calc with mixed tabs and spaces

- lua/ibl/scope_languages.lua
https://github.com/nvim-treesitter/nvim-treesitter/blob/eff88f4e8b71d92bdcaeca6e4f7e1e146b263614/queries/nim/locals.scm#L291-L322
> feat: Add Nim to scope languages

- lua/ibl/inlay_hints.lua
Inlay hint refreshes the buffer async now. IBL needs to refresh after that.
> fix: inlay hint refresh

- lua/ibl/indent.lua
- specs/features/indent_spec.lua
> fix: mixed indent calculation
