lukas-reineke/indent-blankline.nvim

doc/indent_blankline.txt

When installing this plugin using `dein` (and I would assume other plugin managers that auto-generate helptags as well), there is an issue with a duplicate helptag if `indentLine` is also installed:
```
[dein] Error generating helptags:
[dein] Vim(helptags):E154: Duplicate tag "indentLine-changelog" in file ~.cache/dein/.cache/init.vim/.dein/doc/indent_blankline.txt
[dein] function <lambda>1[1]..dein#install#_polling[1]..<SNR>18_install_async[9]..<SNR>18_done[7]..dein#install#_recache_runtimepath[20]..<SNR>18_helptags, line 12
```
This PR changes this tag to be unique to `indent-blankline,` avoiding conflicts.
Thanks for creating this plugin!

doc: correct tag for changelog to avoid duplicate helptag issue

---

autoload/indent_blankline.vim

Works for me so far. Will preserve user `shellslash` setting. Thanks for the help.
See issue #52 for more info.

Fix issue #52 where plugin will not work for files that are not in current working directory

---

lua/indent_blankline/init.lua

Fixes #41.
Using the new `hl_mode` option for `nvim_buf_set_extmark` added recently: https://github.com/neovim/neovim/pull/14065
**Before:**
**After:**
**Known issues:**
This appears to break indent lines on versions of Neovim which do not have the `hl_mode` option, so you might want to wait a few days to merge this for people to update their Neovim.

Show visual selections for indentations

---

doc/indent_blankline.txt
lua/indent_blankline/init.lua
plugin/indent_blankline.vim

This PR adds a list for defining different highlights at different levels with context highlighting. Currently there is no synchronization between brace/paren/other scope delimiter and the indent line color. It is just coincidental that the colors of the braces and the line match in the second image.

Context highlight list

---

plugin/indent_blankline.vim

Some completion engines re-indent the text while cycling through items.
This means text could get hidden behind the indent guides when the
indention becomes lower than when input started.
fix #166

bug: refresh on complete change

---

lua/indent_blankline/init.lua
lua/indent_blankline/utils.lua

Clear the current buffer when `is_indent_blankline_enabled` switches from `true` to `false`.
Needs `schedule_wrap` because of some race condition when starting Neovim.
fix #175

bug: fix buftype exclude

---

doc/indent_blankline.txt
lua/indent_blankline/init.lua
lua/indent_blankline/utils.lua

My attempt at implementing #74. Now fully backwards compatible.
`set list listchars=tab:<->,space:⋅,trail:~,eol:↴`
Ligatures are handled by the terminal, not this plugin.
The new behavior can be activated with `g:indent_blankline_show_whitespace`, which defaults to `false`. There won't be any change to existing behavior when updating without user intervention.
I also added several new variables (with documentation) to customize the appearance of the overlay text. They all default to their `listchars` values, or have appropriate fallbacks. 
```
g:indent_blankline_trail_char
g:indent_blankline_tab_char_start
g:indent_blankline_tab_char_fill
g:indent_blankline_tab_char_end
```

Allow for display of listchars in indentation overlay. (refactor)

---

README.md
doc/indent_blankline.txt
lua/indent_blankline/init.lua
lua/indent_blankline/utils.lua

* Correctly display listchars under the indent guides
Huge thanks to @Daxtorim
* Remove options:
`indent_blankline_space_char` - listchars is used to get the correct space character
fixes #74

Version 2.2.0

---

doc/indent_blankline.txt
lua/indent_blankline/init.lua
lua/indent_blankline/utils.lua

Addressing #195.
I renamed the option `g:indent_blankline_respect_list` to the more descriptive name `g:indent_blankline_disable_with_list`. 
1. If this option is set to true, setting `nolist` will essentially disable the plugin as was implemented in #201.
2. If this option is set to false (default), setting `nolist` will replace all `listchars` with empty spaces (like `nolist` without this plugin) but keep indentation guides.

Allowing to remove all listchars but keep indentation guides with 'set list/nolist'.

---

doc/indent_blankline.txt
lua/indent_blankline/init.lua

This adds an option `max_indent_increase`, which specifies the maximum indent level increase compared to the last normally indented line that make a line a normally indented line. For abnormally indented lines, only the normal indent level is shown. This makes aligned comments look better.

Add option max_indent_increase

---

lua/indent_blankline/init.lua

according to `PackerProfile` this change makes `setup` go from taking ~22ms to ~0.4ms on my machine. unsure why requiring these files is so slow.

speed up setup time by conditionally loading nvim-treesitter.query and nvim-treesitter.indent

---

doc/indent_blankline.txt
lua/indent_blankline/init.lua
lua/indent_blankline/utils.lua

Adds `g:indent_blankline_context_pattern_highlight` option.
It specifies a map of patterns set in `g:indent_blankline_context_patterns` to highlight groups.
When the current matching context pattern is in the map, the context will be highlighted with the corresponding highlight group.
Empty by default
Thank you Gen.F for the idea :pray:

feature: add context-pattern-highlight

---

lua/indent_blankline/init.lua
plugin/indent_blankline.vim

Run init on VimEnter to initialize indents in all open windows.
But also run init on plugin load, in case of lazy loading.

bug: init on enter

---

doc/indent_blankline.txt
lua/indent_blankline/init.lua
lua/indent_blankline/utils.lua
plugin/indent_blankline.vim

* Memoize the find indent function
* Run init on VimEnter to initialize indents in all open windows
* Run init on plugin load to work with lazy loading

Version 2.6.2

---

lua/indent_blankline/init.lua

Fixes bug introduced by 1b554c6183e54b3f1d7266ecc9d3be1aa1a58349, where the ranges table wasn't getting updated at all, effectively nullifying the scrolling optimization.
For some reason when you directly assign a value to a key in `vim.b.my_table`, the table doesn't actually update, so a solution is to assign the table to a local variable, change the key in that local variable, then assign the variable to `vim.b.my_table`. I don't know if it's related to the way neovim accesses values from lua or why this happens, but if you have a better solution let me know.

fix(refresh): fix range updates when scrolling

---

lua/indent_blankline/utils.lua

As described in `:h 'filetype'`, Vim supports compound filetypes, where a dot is used to glue together multiple filetypes. For example, a filetype of "javascript.jest" would indicate that the file contains both "javascript" and "jest" syntax.
Just say the user wants to turn off indent-blankline.nvim in all "javascript" files. The previous implementation meant that they would have to add not only "javascript", but "javascript.jest" and any other dotted filetypes that they might see, because the code was looking for an exact match.
This PR explodes filetypes such as "javascript.jest" into a list-like table of "javascript" and "jest", and it checks each one against the exclusion list individually, as well as jointly.
This means the user can add "javascript" to their …

feat: support dotted filetypes for exclusions

---

.github/workflows/pr_check.yml
.luacheckrc
doc/indent_blankline.txt
lua/indent_blankline/init.lua
lua/indent_blankline/utils.lua

* Support both the concatenated string, as well as the individual `filetypes` in `g:indent_blankline_filetype_exclude` when a buffer has multiple `filetypes`

Version 2.13.0

---

doc/indent_blankline.txt
lua/indent_blankline/init.lua

Hello!
I've added filetype "man" to the list of excluded filetypes. Not as commonly encountered as filetype "help" perhaps but since the Man plugin is builtin and executed through the "K" key sometimes I felt that it was appropriate to add this to the default settings upstream instead of just disabling it on my end.
/ Göran Gustafsson

Added filetype "man" to exclude list

---

doc/indent_blankline.txt
lua/indent_blankline/utils.lua

Ignore treesitter scope context if it is only one line

Version 2.18.1

---

lua/indent_blankline/init.lua

This is a better approach of the previous pr I made (#453). This time instead of hard coding the events I decided to let *the end user* choose what events should run the `IndentBlanklineRefresh` command.
Option name: `refresh_events`
Default value: `{ "CursorMoved" }`
As I mentioned in the commit message please add this to the help tag since I don't know much about that. Thanks!

Add `refresh_events` option

---

doc/indent_blankline.txt
lua/indent_blankline/init.lua

I've added filetype "TelescopePrompt" to the list of excluded filetypes.
Like packer, it's a de facto standard plugin, so I thought it would be nice to have it in the default settings.

Added buftype "prompt" to exclude list

---

doc/indent_blankline.txt

i tried this [this example](https://github.com/lukas-reineke/indent-blankline.nvim/blob/master/README.md#with-custom-gindent_blankline_char_highlight_list) in `README.md`
it did not work and indent lines color was white 
so the reason for this was because i was setting my colorscheme(in after/plugin/color.lua) after my `indent-blankline.nvim` config
and colorschemes will clear all highlights with `highlight clear` before setting their own colors
So why not add a note for anyone using `char_highlight_list` :)
https://github.com/joshdick/onedark.vim/blob/b6b5ffe31a195a3077338d7a506b905e4a51590f/colors/onedark.vim#L49
https://vi.stackexchange.com/questions/3355/why-do-custom-highlights-in-my-vimrc-get-cleared-or-reset-to-default

doc: add note for custom `indent_blankline_char_highlight_list`

---

lua/indent_blankline/init.lua

Currently the context is shown like this. The `match` block is not highlighted.
With the patch, the `match` block is shown as context.

add `match`  to context patterns

---

lua/indent_blankline/init.lua

The treesitter commands for Zig differ, which is why context highlighting did not work. I have added the necessary commands in this PR.

added treesitter support for zig

---

doc/indent_blankline.txt

These extra blanklines were messing up the format highlighting:

doc: Fix man page formatting

---

lua/indent_blankline/init.lua

Although its usefulness may be subject to debate, Ruby includes an `unless` block. This block isn't currently recognized by indent-blankline's `show_current_context` feature.
- Add support for ruby's `unless` blocks
- Fix some inconsistent whitespace
Here is a before and after screenshot.
The cursor is on line 8.
The context line is on lines 4-11 instead of the expected 5-8.
The cursor is on line 8.
The context line is on lines 5-8, which is what one would expect.

Fix for Ruby 'unless' blocks

---

lua/indent_blankline/utils.lua

For some reason `ts_utils` parses comments as `source` causing context parsing to result in an error. This fixes the issue by using `vim.treesitter` instead.

fix problem where context is incorrectly parsed when hovering comments

---

lua/indent_blankline/utils.lua

fixes #606
This could be a neovim issue. Quote from help (note the last sentence):
```
synIDattr({synID}, {what} [, {mode}])			*synIDattr()*
The result is a String, which is the {what} attribute of
syntax ID {synID}.  This can be used to obtain information
about a syntax item.
{mode} can be "gui" or "cterm", to get the attributes
for that mode.  When {mode} is omitted, or an invalid value is
used, the attributes for the currently active highlighting are
used (GUI or cterm).
```
But it seems to only detect that I'm using cterm highlighting when I change colorscheme from within neovim, but not when I set colorscheme from my vimrc. Maybe the "currently active highlighting" is only defined after neovim launches.
Anyways, this seems like a simple fix.

add checks for cterm highlights before highlights reset

---

README.md
doc/indent_blankline.txt

Fixes a couple of typos I found while reading the new docs.
Also removes a duplicate tag for `ibl.config.scope.exclude` that causes an error when building the docs with `lazy.nvim`.

docs: fix typos

---

doc/indent_blankline.txt
lua/ibl/config.lua
lua/ibl/highlights.lua

Add `IblIndent`, `IblWhitespace`, and `IblScope`, that default to `Whitespace` and `LineNr` like before. This allows color schemes to overwrite the colors.
see `:help ibl.highlights`

feat: Add highlight groups

---

lua/ibl/scope_languages.lua

Remove `translation_unit` from c scope because it will cause the whole file to become scope
fix #657

fix: c scope

---

lua/ibl/highlights.lua

This should be tested, but I think this should fix with older Neovim compatibility.
I can test this fully early next week. Thanks to the maintainers for this great project!
Closes #658

fix: add support for Neovim v0.7+

---

lua/ibl/highlights.lua

Correct 'emtpy_dict()' to 'empty_dict()'.

Fix typo in highlights.lua

---

lua/ibl/hooks.lua

It is not always a good idea to pick the highlight color based on the last symbol of the start/end line when using e.g. rainbow-delimiters. E.g. in Lua, I have some functions that look like this: 
```lua
...
... function()
...
end,
```
The current code would pick highlights based on the "," (no highlight) and the ")" (wrong highlight, this is one level deeper than `function`-`end`). 
I have had better luck picking based on the actual scope start/end, and then I have left the old last symbol on the start/end line as a fallback. This picks the color from `function` and `end` in the above example.

Improve scope highlight hook

---

lua/ibl/scope_languages.lua

All of these scopes cover the whole file, so are not useful to display

fix: remove top level scopes

---

lua/ibl/scope.lua
lua/ibl/utils.lua

When a buffer is displayed in multiple windows, on different tabs, use the window from the current tab.

refactor: favor same tab win

---

lua/ibl/init.lua

fix: support single buffer enabled without global

---

lua/ibl/config.lua

The documentation was not consistent with the code and comments. I think the version that is described in the documentation is more useful, so this should be what the code does.
I think it is fair to classify this as a bug, so this is not a breaking change. But it does behave differently now. If you want the old behavior, call `ibl.setup` once before.

fix: config overwrite

---

lua/ibl/highlights.lua
lua/ibl/hooks.lua
lua/ibl/indent.lua
lua/ibl/init.lua
lua/ibl/scope.lua
lua/ibl/utils.lua
lua/ibl/virt_text.lua

Most of the vim.tbl_* functions internally validate the input. This can be very expensive for hot loops.
This implements an internal version of those functions without validation.
fix #776

refactor: implement own version of vim.tbl_* without validate

---

lua/ibl/init.lua

There is a small race condition where this could lead the multiple calls of refresh.

refactor: debounce

---

doc/indent_blankline.txt

I think adding this to the docs will help clarify the use of `ibl.overwrite()`.

docs: note that overwrite should be after setup

---

lua/ibl/scope_languages.lua

Since I was already making the other pull request, I thought I might as well add this one too. See: #763

fix: typo in `arduino`

---

lua/ibl/scope_languages.lua

Adds language `risor`: <https://risor.io/>
I'm currently creating a tree-sitter grammar for it: <https://github.com/applejag/tree-sitter-risor>
Took me a while of debugging why the scope feature didn't work out-of-the box. I thought for so long that my grammar was wrong 😅 never considered that it was ibl
I was not able to add the language just from configs though. Would've been nice if that was possible. But currently ibl just skips if it does not contian the language in its hardcoded list:
https://github.com/lukas-reineke/indent-blankline.nvim/blob/d4c718467d35bc93714425a7102d82e7e5065280/lua/ibl/scope.lua#L60-L63

Added language: risor

---

doc/indent_blankline.txt
lua/ibl/config.lua
lua/ibl/init.lua
lua/ibl/utils.lua

This pull request moves the calculation of the scope index out of the main loop, since we want to be able to figure this out without including lines all the way from the start of the scope if we are in the middle of a very long scope. 
Since we no longer need to include as many lines to get good highlighting, I also lowered the default value of `viewport_buffer.max` from 500 to 60. I think we can lower both `min` and `max` even more, but at that point it becomes a question of personal preference. I picked 60, since that should about cover one full screen for most people (I think?). 
Furthermore, I added a comparison between the start line and end line whitespace tables, and we use the smaller one to calculate the scope index. This fixes #752, and I can't think of any normal formatting …

fix: move some scope calculations out of main loop

---

lua/ibl/init.lua
lua/ibl/virt_text.lua
specs/features/virt_text_spec.lua

With the changes of #795, the scope indent and the scope start line indent are not necessarily the same anymore. The scope start underline padding needs to take this into account.
Without fix:
With fix:

fix: scope start padding

---

doc/indent_blankline.txt
lua/ibl/autocmds.lua
lua/ibl/config.lua
lua/ibl/config.types.lua
lua/ibl/init.lua

Opt-out with `ibl.config.indent.repeat_linebreak = false`.
Close #577

feat: repeat indent guides on wrapped lines with 'breakindent'

---

lua/ibl/scope_languages.lua

This adds git_config to scope_languages. From what I can tell `section` is the only scope (the format is pretty simple).

feat: add git_config to scope_languages

---

lua/ibl/scope_languages.lua

Add "vue", "svelte" & "angular" to scope_languages

---

lua/ibl/utils.lua

v3.6.0's release had a breaking change when it changed what version of neovim it supported. This reverts the breaking change if using an older version of neovim but still uses the new, non-deprecated API if it's available. This is particularly important immediately after a release because package managers haven't all caught up to providing 0.10 and it may not be widely available or even used in stable environments until the first path release. I think if we don't want to merge this we should at least revert the v3.6.0 release and tag v4 to indicate the breaking nature of the release.
Thanks so much for all your effort supporting and developing this great plugin!

fix: only use `vim.iter` if available to avoid accidental breaking change

---

lua/ibl/init.lua
lua/ibl/utils.lua

Neovim 0.10 changed the behavior for when `'foldtext'` is empty. It now displays the line normally with highlighting.
`vim.fn.foldtextresult` does however not reflect this change and returns the previous foldtext, like `+--  4 lines folded`. This breaks the current implementation which checks if indentation lines can be displayed over the foldtext.
So until (if ever) this gets fixed, we need to do a custom check.
fix #901

feat: support empty foldtext in nvim 0.10

---

lua/ibl/config.lua
lua/ibl/virt_text.lua

`strdisplaywidth` is broken when called while loading a buffer. For example on `BufReadPost`.
fix #832

fix: use `strwidth` instead of `strdisplaywidth`

---

lua/ibl/scope_languages.lua

I think these are the only two nodes we need.  I been using this for a little while and the only problem I've noticed is due to a treesitter mistake (https://github.com/tree-sitter-perl/tree-sitter-perl/issues/177).

Add Perl to scope languages

---

lua/ibl/scope_languages.lua

This was updated recently in php treesitter
https://github.com/nvim-treesitter/nvim-treesitter/commit/ec8776ed9ef56ffe7a61e67b64d5d6b6aba2c631
https://github.com/tree-sitter/tree-sitter-php/commit/0d3959bbd404c91535c8f913586561094f41fe54

fix(php): anonymous_function_creation_expression replaced with anonymous_function

---

.gitignore

`:helptags ALL` creates this file and `git status` then keeps telling me about it. Other nvim plugins have this in their .gitignores, so add it here as well to silence it.

chore: add doc/tags to .gitignore

---

README.md
lua/ibl/hooks.lua
lua/ibl/scope.lua

Node types for languages defined in `:help ibl.config.scope.include.node_type` will work, even if the language does not have support out of the box.
fix #926

feat: Support user defined scope languages

---

lua/ibl/scope.lua

If the language is not listed in the languages "officially" supported by ibl, `scope[lang]` is `nil`.

fix: scope logic with unknown language

---

lua/ibl/init.lua
lua/ibl/scope.lua

There seems to be a bug in treesitter that allows an infinite loop of node parents, if the node is empty.
IBL doesn't care about the node if it's empty anyway, so we can just ignore them.
fix #930

fix: don't allow empty scope

---

lua/ibl/config.lua
lua/ibl/hooks.lua
lua/ibl/utils.lua

The form of `vim.validate` that takes a spec table as input was deprecated in https://github.com/neovim/neovim/pull/30855 and plugins should now use the faster version introduced in https://github.com/neovim/neovim/pull/28977.
This PR adds a new utility function to use the faster version if available. Also defined the existing `utils.validate` function to avoid confusion with the new utility function.

feat: use faster version of `vim.validate` if available

---

lua/ibl/virt_text.lua
specs/features/virt_text_spec.lua

fix: leadmultispace and multispace

---

lua/ibl/config.lua

Looks like we're passing in `char` when trying to validate `tab_char`.

fix: correct copy-pasta in config.indent validation

---

lua/ibl/config.lua

Removes one of the nested conditionals:
```lua
if config.exclude then
if config.exclude then
```

refactor: remove redundant conditional

---

lua/ibl/inlay_hints.lua

Neovim 11 has changed the inlay hint namespace name.

fix: fix inlay hint scope underline
